FROM ubuntu:17.10
ARG REPO_PATH
RUN apt-get update -y && \
    apt-get install -y software-properties-common && \
    apt-get update -y && \
    apt-get install -y lib32stdc++6 lib32z1 lib32z1-dev lib32ncurses5 libc6-dev libgmp-dev libmpc-dev libmpfr-dev libxslt-dev libxml2-dev m4 ncurses-dev openssh-client wget openjdk-8-jdk python2.7 python-pip git unzip && \
    rm -rf /var/lib/apt/lists/* && \
    apt-get autoremove -y && \
    apt-get clean

ENV ANDROID_SDK_FILENAME android-sdk_r24.4.1-linux.tgz
ENV ANDROID_SDK_URL https://dl.google.com/android/${ANDROID_SDK_FILENAME}
ENV ANDROID_API_LEVELS android-27
ENV ANDROID_BUILD_TOOLS_VERSION 27.0.3
ENV ANDROID_HOME /usr/local/android-sdk-linux
ENV PATH ${PATH}:${ANDROID_HOME}/tools:${ANDROID_HOME}/platform-tools
RUN cd /usr/local/ && \
    wget -q ${ANDROID_SDK_URL} && \
    tar -xzf ${ANDROID_SDK_FILENAME} && \
    rm ${ANDROID_SDK_FILENAME} 
RUN echo y | android update sdk --no-ui -a --filter ${ANDROID_API_LEVELS}
RUN echo y | android update sdk --no-ui -a --filter extra-android-m2repository,extra-android-support,extra-google-google_play_services,extra-google-m2repository
RUN echo y | android update sdk --no-ui -a --filter tools,platform-tools,build-tools-${ANDROID_BUILD_TOOLS_VERSION}
RUN rm -rf ${ANDROID_HOME}/tools && unzip ${ANDROID_HOME}/temp/*.zip -d ${ANDROID_HOME}
RUN git clone $REPO_PATH /android-proof-env/android-proof
RUN cd /android-proof-env/android-proof/src/ && \
    ./gradlew clean assembleRelease
CMD python /android-proof-env/android-proof/deterministic_build/apkdiff.py /android-proof-env/android-proof/src/app/build/outputs/apk/release/app-release-unsigned.apk /android-proof-env/android-proof/deterministic_build/original_apk/add-reproducible-build-signed.apk